<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Spatie\Permission\Models\Role as SpatieRole;
use Illuminate\Support\Str;

class Role extends SpatieRole
{
    use HasUuids;

    protected $primaryKey = 'id';
    protected $fillable =[
        'id',
        'name',
        'guard_name'
    ];
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (empty($model->{$model->getKeyName()})) {
                $model->{$model->getKeyName()} = Str::uuid7()->toString();
            }
        });
    }

    public function getKeyName()
    {
        return 'id'; // TODO: Change the autogenerated stub
    }

    public function getIncrementing(): bool
    {
        return false;
    }

    protected $keyType = 'string';

}
